# conda env create --file environment.yml
# mamba env create --file environment.yml
name: portfolio
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
